[package]
name = "rust-trending"
version = "0.4.0"
authors = ["Kangwook Lee <pbzweihander@gmail.com>"]
edition = "2018"
repository = "https://github.com/pbzweihander/rust-trending"
readme = "README.md"
license = "MIT"

[dependencies]
anyhow = "1.0.41"
egg-mode = { version = "0.16.0", features = ["rustls_webpki"], default-features = false }
env_logger = "0.8.4"
log = "0.4.14"
redis = { version = "0.20.2", features = ["aio", "tokio-comp"] }
reqwest = { version = "0.11.4", features = ["rustls-tls"], default-features = false }
scraper = "0.12.0"
serde = { version = "1.0.126", features = ["derive"] }
tokio = { version = "1.8.1", features = ["rt-multi-thread", "time", "macros"] }
toml = "0.5.8"
