[interval]
post_ttl = 604800
fetch_interval = 60
post_interval = 60

[redis]
url = "redis://localhost:6379/0"

[twitter]
consumer_key = ""
consumer_secret = ""
access_key = ""
access_secret = ""

[denylist]
names = []
authors = []
