[interval]
tweet_ttl = 604800
fetch_interval = 60
tweet_interval = 60

[redis]
url = "redis://localhost:6379/0"

[twitter]
disabled = true
consumer_key = ""
consumer_secret = ""
access_key = ""
access_secret = ""

[blacklist]
names = []
authors = []
