version: '3'

services:
  redis:
    image: redis:4-alpine

  bot:
    image: ghcr.io/pbzweihander/rust-trending:latest
    depends_on:
      - redis
    environment:
      - RUST_LOG=info
    volumes:
      - /srv/rust-trending/config.toml:/config.toml
