version: '3'

services:
  redis:
    image: redis:4-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

  bot:
    image: pbzweihander/rust-trending:latest
    depends_on:
      - redis
    volumes:
      - /srv/rust-trending/config.toml:/app/config.toml

volumes:
  redis-data:
